// packages/project-vue3/src/App.vue
<script setup>
import { resolveAB } from '@wlk/utils';
import numIndex from '@wlk/apis';
import {num} from '@wlk/apis/userApi/user.js'
const res = resolveAB(1,4);
</script>

<template>
  <div>
    monorepo-vue
    <hr>
    {{ res }}-- {{ numIndex }} -- {{ num }}
  </div>
</template>

<style scoped>
</style>

// packages/project-react/src/App.jsx
import { useState } from 'react'
import { resolveAB } from '@wlk/utils';
import numIndex from '@wlk/apis';
import {num} from '@wlk/apis/userApi/user.js'

function App() {
  const [count, setCount] = useState(0)
  const handleClick = () => {
    setCount(n => n + 1)
  }

  return (
    <>
      {count} - <button onClick={handleClick}>+</button>
      <hr />
      {num} --- {numIndex} --- {resolveAB(1, 2)}
    </>
  )
}

export default App
